Resources/Include/MDDBeep.h
Resources/Include/MDDCANMessage.h
Resources/Include/MDDComedi.h
Resources/Include/MDDJoystick.h
Resources/Include/MDDKeyboard.h
Resources/Include/MDDMinimalSerialPackager.h
Resources/Include/MDDOperatingSystem.h
Resources/Include/MDDRealtimeSynchronize.h
Resources/Include/MDDSerialPackager.h
Resources/Include/MDDSerialPort.h
Resources/Include/MDDSharedMemory.h
Resources/Include/MDDSocketCAN.h
Resources/Include/MDDSoftingCAN.h
Resources/Include/MDDUDPSocket.h
Resources/Include/MDDUtilities.h

using astyle with options ```--indent=spaces --style=java --break-closing-brackets --add-brackets --indent-switches```

Fix the messy indents of C headers

---

Modelica_DeviceDrivers/Resources/Include/MDDSerialPort.h

* Change third argument (input Integer) of MDD_serialPortSend from int* to int
@bernhard-thiele Please double-check.

Make MDDSerialPort.h ANSI C compliant

---

Modelica_DeviceDrivers/Blocks/Packaging/SerialPackager.mo

See modelica/Modelica_DeviceDrivers/#69
@bernhard-thiele Please double-check and test.

Add start and fixed attributes to Get models of SerialPackager

---

build.drone.io.txt

Document the updated drone.io build commands on legacy Ubuntu 12.04

Update drone.io build commands

---

Modelica_DeviceDrivers/Resources/Include/MDDSerialPort.h

* Gradually read in temporary and thread-local buffer `receiveBufferTmp` until it is full
* Copy complete temporary buffer to read buffer (guarded by lock)
* Remove `receiveError` from struct `MDDSerialPort` and make it a thread-local variable
* Close `rdEvnt` handle
* Thank you, @vwaurich, for bringing up this topic in #127 and providing an early fix

Fix serial port reading on Windows

---

Modelica_DeviceDrivers/Resources/Include/MDDUDPSocket.h
Modelica_DeviceDrivers/Resources/src/ITI_ModelicaDeviceDrivers/MDDWrapper.c

SimulationX has some known issue with ModelicaMessage from a Win thread.

Avoid ModelicaMessage in MDD_udpReceivingThread for ITI_MDD

---

Modelica_DeviceDrivers/Resources/Include/MDDSharedMemory.h

* Remove 8 byte buffer overhead for lock and buffer size
* Use semaphore (instead of lock within shared memory buffer) consistent with Linux implementation
This PR supersedes #136.

Rewrite shared memory buffer synchronization (Win)

---

Modelica_DeviceDrivers/EmbeddedTargets/AVR/Functions/Digital/InitRead.mo
Modelica_DeviceDrivers/EmbeddedTargets/AVR/Functions/Digital/InitWrite.mo
Modelica_DeviceDrivers/EmbeddedTargets/AVR/Functions/Digital/LCD.mo

Avoid the multiple definition import of MLS 3.3

---

Modelica_DeviceDrivers/Resources/doc/Modelica2017/caption.sty
Modelica_DeviceDrivers/Resources/doc/Modelica2017/caption3.sty
Modelica_DeviceDrivers/Resources/doc/Modelica2017/subcaption.sty

Needed for legacy Ubuntu 12.04 on drone.io

Add caption, caption3 and subcaption

---

Modelica_DeviceDrivers/Resources/doc/Modelica2017/modelica2017_Modelica_DeviceDrivers.tex

Modelica2017 Added text for embedded targets

---

Modelica_DeviceDrivers/EmbeddedTargets/AVR/Blocks/DigitalReadBoolean.mo
Modelica_DeviceDrivers/EmbeddedTargets/AVR/Blocks/DigitalWriteBoolean.mo
Modelica_DeviceDrivers/EmbeddedTargets/AVR/Blocks/package.order
Modelica_DeviceDrivers/EmbeddedTargets/AVR/Examples/Arduino/UNO/Blink.mo
Modelica_DeviceDrivers/EmbeddedTargets/AVR/Functions/Digital/read.mo

Rewrote the Blink example to use the added blocks.

Add Digital read/write blocks

---

Modelica_DeviceDrivers/Resources/doc/Modelica2017/modelica2017_Modelica_DeviceDrivers.bib
Modelica_DeviceDrivers/Resources/doc/Modelica2017/modelica2017_Modelica_DeviceDrivers.tex

@bernhard-thiele @tbellmann This is the result of my today's evaluation of the current state of the proposed Modelica2017 article. I also added several TODOs in the `\TBEU` notes to improve readability or clarify certain topics. I leave it as PR for you since it is a convenient way to inspect all those tiny changes of several commits summarized in one GitHub page.
This is for #126.

Add minor corrections and TODOs for Modelica2017 article

---

Modelica_DeviceDrivers/EmbeddedTargets/AVR/Functions/Analog.mo
Modelica_DeviceDrivers/EmbeddedTargets/AVR/Functions/Digital/LCD.mo

Downgrade to MLS 3.2

---

Modelica_DeviceDrivers/Resources/doc/Modelica2017/modelica2017_Modelica_DeviceDrivers.tex

@sjoelund Please merge such that I can continue w/o conflicts tomorrow. Thanks.

Article contribution 16/01

---

Modelica_DeviceDrivers/Resources/doc/Modelica2017/modelica2017_Modelica_DeviceDrivers.tex

@sjoelund Please review and merge such that I can continue w/o conflicts tomorrow. Thanks.

Article contribution 17/01

---

Modelica_DeviceDrivers/Resources/doc/Modelica2017/modelica2017_Modelica_DeviceDrivers.tex

@sjoelund Please review and merge such that I can continue w/o conflicts tomorrow. Thanks.

Article contribution 18/01 

---

Modelica_DeviceDrivers/Resources/doc/Modelica2017/modelica2017_Modelica_DeviceDrivers.tex

This way, we know if noindent should be used or not.

Use either `h` or `tb` for figures

---

Modelica_DeviceDrivers/Resources/doc/Modelica2017/modelica2017_Modelica_DeviceDrivers.tex

@sjoelund Please review and merge. Thanks.

Article contribution 19/01

---

Modelica_DeviceDrivers/Resources/doc/Modelica2017/modelica2017_Modelica_DeviceDrivers.tex

Article contribution 16/03

---

Modelica_DeviceDrivers/Resources/doc/Modelica2017/modelica2017_Modelica_DeviceDrivers.tex

I run LaTeX2RTF and checked the spelling (U.S. English) in MS Word.

Article contribution 23/03

---

Modelica_DeviceDrivers/Resources/Include/MDDSerialPackager.h

Do not swap bytes of input or pkg data

---

Modelica_DeviceDrivers/Resources/License.txt
Modelica_DeviceDrivers/Resources/test/Communication/test_EndiannessConversion.c
Modelica_DeviceDrivers/Resources/test/Communication/test_MDDSerialPackager.c
Modelica_DeviceDrivers/Resources/test/Communication/test_MDDSerialPort.c
Modelica_DeviceDrivers/Resources/test/Communication/test_MDDSharedMemory.c
Modelica_DeviceDrivers/Resources/test/Communication/test_MDDTCPIPSocketClient.c
Modelica_DeviceDrivers/Resources/test/Communication/test_MDDUDPSocket.c
Modelica_DeviceDrivers/Resources/test/HardwareIO/test_MDDComedi.c
Modelica_DeviceDrivers/Resources/test/InputDevices/test_MDDJoystick.c
Modelica_DeviceDrivers/Resources/test/InputDevices/test_MDDKeyboard.c
Modelica_DeviceDrivers/Resources/test/InputDevices/test_MDDSpaceMouse.c
Modelica_DeviceDrivers/Resources/test/SocketCAN/test_MDDSocketCAN.c
Modelica_DeviceDrivers/Resources/test/SoftingCAN/test_MDDCANMessage.c
Modelica_DeviceDrivers/Resources/test/SoftingCAN/test_MDDSoftingCAN.c
Modelica_DeviceDrivers/Resources/test/Util/test_MDDMapIntInt.c
Modelica_DeviceDrivers/Resources/test/Util/test_MDDMapIntpVoid.c
Modelica_DeviceDrivers/Resources/test/Util/test_MDDUtilities.c
Modelica_DeviceDrivers/UsersGuide.mo
Modelica_DeviceDrivers/package.mo

Reflect company name change

---

.travis.yml

Thank you @dietmarw for spotting the typo.

Fix package name to libx11-dev (for Travis CI)

---

Modelica_DeviceDrivers/Resources/Include/MDDRealtimeSynchronize.h

Fix C89 compilation (and indents)

---

Modelica_DeviceDrivers/Resources/Include/MDDUDPSocket.h

* Utilize WSAPoll on Windows and avoid memcpy between receiveBuffer and receiveBufferTmp
* Remove receiveBufferTmp from MDDUDPSocket_s on Windows
* Fix lock on nReceivedBytes on Linux
* Add missing break statement in switch on Linux
close #240

Revise UDP read thread implementation

---

Modelica_DeviceDrivers/Resources/Include/MDDLCM.h
Modelica_DeviceDrivers/Resources/Include/MDDSerialPort.h
Modelica_DeviceDrivers/Resources/Include/MDDSocketCAN.h
Modelica_DeviceDrivers/Resources/Include/MDDTCPIPSocket.h
Modelica_DeviceDrivers/Resources/Include/MDDUDPSocket.h
Modelica_DeviceDrivers/Resources/test/Util/ModelicaUtilities.c

* Check return value of sendto
* Raise warnings in case of disconnects or if sendto sends less bytes than expected
* Update messages

Some proposed changes for communication drivers

---

Modelica_DeviceDrivers/Resources/Include/MDDSerialPackager.h

Need to escape backslash in string

Fix error message

---

Modelica_DeviceDrivers/Resources/CMakeLists.txt
Modelica_DeviceDrivers/Resources/CTestCustom.cmake

Exclude interactive tests from CTest

---

Modelica_DeviceDrivers/Resources/Include/MDDUtilitiesMAC.h

The Linux implementation of MDD_utilitiesGetMACAddress iterates over all available interfaces.
Close #260

Iterate over all available interfaces

---

Modelica_DeviceDrivers/Resources/Include/MDDAVRDigital.h

DigitalWrite function wasn't working with push button. Fixed it by making changes in **DigitalWriteBoolean.mo** and **MDDAVRDigital.h**.
Thanks,
Close #229

AVR: Fixed digital reading of inputs

---

Modelica_DeviceDrivers/UsersGuide.mo
README.md

Update the links after moving the repository.

Fix Travis CI links

---

.gitmodules
.travis.yml
Modelica_DeviceDrivers/Resources/CMakeLists.txt
Modelica_DeviceDrivers/Resources/README.md
Modelica_DeviceDrivers/Resources/test/CMakeLists.txt
Modelica_DeviceDrivers/Resources/test/OperatingSystem/CMakeLists.txt
Modelica_DeviceDrivers/Resources/test/OperatingSystem/test_MDDRealtimeSynchronize.cpp
Modelica_DeviceDrivers/Resources/thirdParty/Readme.txt
README.md
git-archive-all.sh

- Googletest library sources added below Resources/thirdParty/googletest
- Added Resources/test/OperatingSystem/test_MDDRealtimeSynchronize.cpp
as googletest usage example (all test_MDDRealtimeSynchronize_* as
unit tests)
- Related to cmake versioning discussion in #286

Experiment using googletest for unit testing

---

Modelica_DeviceDrivers/Resources/Include/MDDUtilitiesMAC.h

getMACAddress() in Linux should now also work for interfaces which are not
connected. Fixes #263.

Similar getMACAddress() in Linux and Windows

---

Modelica_DeviceDrivers/EmbeddedTargets/AVR/Examples/SBHS/Board.mo
Modelica_DeviceDrivers/Utilities/Icons/GenericIC.mo

This fixes the two issues pointed out in #316.

Fix SBHS.Board issues

---

Modelica_DeviceDrivers/Blocks/Communication.mo
Modelica_DeviceDrivers/Communication/SerialPort.mo
Modelica_DeviceDrivers/Resources/Include/MDDSerialPort.h
Modelica_DeviceDrivers/Resources/test/Communication/test_MDDSerialPort.c

Closes #368.
@sertho @max-privato FYI
Reminder: ToDo before v2.2.0 release: Recompile ITI_MDD.dll.

Add byte size parameter for number of data bits of serial port communication
